---
title: "ggplot Homework"
author: "Nathan Strozewski"
date: "2022-09-27"
output: html_document
---

# Preparation

## Load libraries

```{loading_libraries}
library(dplyr)
library(readr)
library(visdat)
library(ggplot2)
library(ggridges)
library(forcats)
```

## Set theme

```{setting_theme}
theme_set(theme_bw(base_size=12))
```

## Load dataset

```{loading_dataset}
ice <- read_csv("http://biol607.github.io/homework/data/NH_seaice_extent_monthly_1978_2016.csv") |>
   mutate(Month_Name = factor(Month_Name), # encodes the  month name as a factor
         Month_Name = fct_reorder(Month_Name, Month)) # helps with mapping 1D displays
```

# Explore the basic properties of the data

```{explore_dataset}
str(ice)
summary(ice)
vis_dat(ice)
```

## Make a boxplot showing the variability in sea ice extent every month. 

```{ice_boxplot}
extent_dist <- ggplot(data = ice,
                      mapping = aes(x = Extent,
                                    y = Month_Name))
extent_dist

extent_dist +
  geom_boxplot(size = 1, alpha = 0.5, 
               show.legend = TRUE, notch = TRUE,
               fill = "salmon")
```

## Use ggridges

```{ice_ggridges}
extent_dist +
  geom_density_ridges(scale = 1, alpha = 0.5,
                      mapping = aes(fill = Month_Name))
```

### Notes:
    1. Numerical values must be plotted on the x-axis
    2. Categorical values should be plotted on the y-axis
    3. A group aesthetic is needed for numerical variables

# Groups from the Coninuous

## Test cut_interval(1:10, n = 5)

```{ci_test}
cut_interval(1:10, n =5)
```

## Plot sea ice by year, with different lines for different months

```{ice_yearly_plot}
ice_yearly <- ggplot(data = ice, 
                     aes(x = Year,
                     y = Extent,
                     group = Month_Name))
ice_yearly

ice_yearly + 
  geom_line(aes(color = Month_Name))
```

## Use facet_wrap and cut_interval(Month, n=4) to split the plot into seasons

```{ice_seasons_plot}
ice_seasons <- ggplot(data = ice,
                      aes(x = Year,
                          y = Extent,
                          group = Month_Name))+
  geom_line(aes(color = Month_Name))

ice_seasons+
  facet_wrap(vars(cut_interval(Month, n = 4)))
```

## Plot sea ice by month with different lines for different years

```{ice_months_plot}
ice_months <- ggplot(data= ice,
                     color = factor(Year),
                     aes(x = Month,
                         y = Extent,
                         group = Year))
ice_months

ice_months +
  geom_line()
```

## Change color by year

```{ice_months_plot_color_change}
ice_months +
  geom_line(aes(color = Year))
```

## Apply a different theme, axis-labels, etc.

```{ice_months_plot_labels}
ice_months_formatted <- ice_months +
  labs(title = "Monthly Sea Ice Extent by Year",
       x = "Month",
       y = "Sea Ice Extent",
       color = "Year") +
  theme_light() +
  geom_line((aes(color = factor(Year))))
ice_months_formatted
```

# Animate

```{ice_animation}
library(gganimate)

ice_months_colored_animate <- ice_months +
  theme_light() +
  geom_line((aes(color = factor(Year))))  +
  labs(title = "Monthly Sea Ice Extent: {Year}",
       x = "Month",
       y = "Sea Ice Extent",
       color = "Year") +
  transition_time(Year) +
  ease_aes('linear')
 
animate(ice_months_colored_animate)
ice_months_colored_animate
```

## Make something new & awesome

```{new_awesome_ice}
ice_cool <- ggplot(ice, 
                   aes(x = Year,
                       y = Extent)) +
  labs(title = "Yearly Sea Ice by Month",
       x = "Year",
       y = "Sea Ice Extent",
       color = "Month") +
  theme_classic() +
  geom_line(aes(color = factor(Month_Name))) +
  transition_states(Month_Name, transition_length = 5)
ice_cool
```

## Tidy Tuesday

```{tide_tuesday_practice}
artists <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-09-27/artists.csv')

str(artists)
summary(artists)

artists_MA <- filter(artists, state == "Massachusetts")

artists_MA_pretty <- ggplot(artists_MA,
                       aes(x = artists_n,
                           y = type))  +
  labs(title = "Number of Artists per Type",
         subtitle = "in Massachusetts",
         x = "Number of Artists in MA",
         y = "Type of Artist") +
  scale_color_discrete() +
  theme_classic() +
  geom_violin(aes(color = factor(type)))

artists_MA_pretty
```

# Meta Questions #

## Question 1:
### How confident were you in thinking about making figures before this week?
    1. I had no idea how to make figures using RStudio before this week
    
### How about after after grappling with ggplot and the grammer of graphics philosophy?
    1. I feel confident that I can figure out how to make a figure in RStudio now.
    2. It might be really difficult and take a lot of time
    3. But I now know the basic principles and resources I can use
    
## Question 2:
### What’s your favorite think about data visualization?
    1. Being able to convey complicated information to someone without expertise in the subject
    2. Also, gganimate is so cool and I can't wait to play around with that more
    
## Question 3:
### How much time did this take you, roughly?
    1. ~3-4 hours
    2. I may have been able to complete this quicker but I did not have the bandwidth this week to focus on this task for extended periods of time
    
## Question 4:
### Please give yourself a weak/sufficient/strong assessment on this assigment
    1. Somewhere between sufficient and strong
    2. I was able to figure out how to complete all pieces of the assignment
    3. But it took me quite a bit of work to figure out how
    4. I spent a lot of time troubleshooting small misunderstandings or mistakes on my part
    5. With continued practice, I am confident I can utilize ggplot very well
